version: '2'

networks:
  risethesun:
    ipam:
      config:
      - subnet: 11.11.11.0/24

services:
  apache2:
    image: httpd
    container_name: apache
    volumes:
    - ../tksunrise/:/tksunrise
    - ./apache2/log/:/var/log/apache2/
    ports:
    - "80:80"
    - "443:443"
    links:
    - php7.2
    networks:
      risethesun:
        ipv4_address: 11.11.11.1
  node:
    image: node
    container_name: node
    volumes:
    - ../tksunrise/:/tksunrise
    ports:
    - "80:80"
    - "443:443"
    networks:
      risethesun:
        ipv4_address: 11.11.11.2
  php7.2:
    build:
      context: .
      dockerfile: php7.2/Dockerfile
    container_name: php7.2
    volumes:
    - ../tksunrise/:/tksunrise
    links:
    - memcached
    - postgres
    networks:
      risethesun:
        ipv4_address: 11.11.11.3
  postgres:
    image: postgres:10.1
    container_name: postgres
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: tksunrise
      POSTGRES_PASSWORD: tksunrise
    networks:
      risethesun:
        ipv4_address: 11.11.11.4
  mongodb:
    image: mongo:2.4.14
    container_name: mongodb
    ports:
    - "27017:27017"
    networks:
      risethesun:
        ipv4_address: 11.11.11.5
  memcached:
    image: memcached:alpine
    container_name: memcached
    networks:
      risethesun:
        ipv4_address: 11.11.11.6